### PR TITLE
Add option to pretty print to publish!

### PR DESCRIPTION
**Pull request by MawiraIke**
Fixes issue #25.

Examples,
1. viz
Original https://gist.github.com/MawiraIke/16ade4d08cbbd0fddce21c40858d50af
With pretty print option on, https://gist.github.com/MawiraIke/00fb697a70eca9312f23820a25476541

2. json
Original https://gist.github.com/MawiraIke/7f43cab3abde06031a318aef3815be5a
With pretty print option on, https://gist.github.com/MawiraIke/f3e9d39f700cae913b879b0289b3231f

### CODE REVIEW

**Comment by MawiraIke** [comment]
Not related to this, I would like to ask if the following line in index.html is intentional
```<script src="js/oz.js" type="text/javascript"></script>```
instead of 
```<script src="js/compiled/oz.js" type="text/javascript"></script>```
Took me a while before i noticed this while debugging, while i was experiencing the "pay no attention" message.

**Comment by metasoarous** [comment]
Hi @MawiraIke! Thanks so much for submitting this. This is a great little addition, and I'm happy to merge it. Sorry for letting it slip through the cracks for a bit though.

Thanks again!

**Comment by MawiraIke** [comment]
Anytime 👍, always a pleasure contributing to this awesome library.

**Comment by metasoarous** [comment]
You're entirely too kind :-)

**Pull request merged**
